//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPoeAgriEnergyPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgriEnergyDBEntities : DbContext
    {
        public AgriEnergyDBEntities()
            : base("name=AgriEnergyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EventEnrollment> EventEnrollments { get; set; }
        public virtual DbSet<EventsTB> EventsTBs { get; set; }
        public virtual DbSet<Farmer> Farmers { get; set; }
        public virtual DbSet<Grant> Grants { get; set; }
        public virtual DbSet<GreenMarket> GreenMarkets { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PostsTB> PostsTBs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<RepliesTB> RepliesTBs { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
