//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPoeAgriEnergyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventsTB()
        {
            this.EventEnrollments = new HashSet<EventEnrollment>();
        }
    
        public int Event_ID { get; set; }
        public string Event_Name { get; set; }
        public string Category { get; set; }
        public decimal Product_Price { get; set; }
        public int Farmer_ID { get; set; }
        public string Event_Image { get; set; }
        public string Description { get; set; }
        public string FarmerName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventEnrollment> EventEnrollments { get; set; }
        public virtual Farmer Farmer { get; set; }
    }
}
