//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPoeAgriEnergyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEnrollment
    {
        public int EnrollmentID { get; set; }
        public int Event_ID { get; set; }
        public Nullable<int> Farmer_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EventsTB EventsTB { get; set; }
        public virtual Farmer Farmer { get; set; }
    }
}
