//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPoeAgriEnergyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grant
    {
        public int GrantID { get; set; }
        public string GrantName { get; set; }
        public string GrantDescription { get; set; }
        public string GrantGroup { get; set; }
    }
}
