//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPoeAgriEnergyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenMarket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GreenMarket()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int GreenMarket_ID { get; set; }
        public string Product_Name { get; set; }
        public int Quantity { get; set; }
        public string Category { get; set; }
        public decimal Product_Price { get; set; }
        public int Farmer_ID { get; set; }
        public string Product_Image { get; set; }
        public string Description { get; set; }
        public string FarmerName { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
