//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPoeAgriEnergyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepliesTB
    {
        public int ReplyID { get; set; }
        public int PostID { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual PostsTB PostsTB { get; set; }
    }
}
