//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPoeAgriEnergyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string BuyerName { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerAddress { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string CVV { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string FarmerName { get; set; }
        public Nullable<int> GreenMarketID { get; set; }
    
        public virtual GreenMarket GreenMarket { get; set; }
        public virtual User User { get; set; }
    }
}
